version: '3'
services:
  jupyter:
    container_name: jupyter_notebook
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan/work
    command: ["start-notebook.sh", "--NotebookApp.token=''"]
